# Generated by Django 5.1.6 on 2025-05-03 18:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('URGENCE', "Fonds d'urgence"), ('ACHAT', 'Achat important'), ('VACANCES', 'Vacances'), ('EDUCATION', 'Éducation'), ('RETRAITE', 'Retraite'), ('DETTE', 'Remboursement de dette'), ('AUTRE', 'Autre')], max_length=20)),
                ('montant_cible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_cible', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIF', 'En cours'), ('TERMINE', 'Atteint'), ('PAUSE', 'En pause'), ('ABANDONNE', 'Abandonné')], default='ACTIF', max_length=20)),
                ('contribution_auto', models.BooleanField(default=False)),
                ('montant_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('frequence_contribution', models.CharField(blank=True, max_length=20, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_realisation', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('objectif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='goals.goal')),
            ],
        ),
        migrations.DeleteModel(
            name='Objectif',
        ),
    ]
