# Generated by Django 5.1.6 on 2025-05-03 19:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_contribution_delete_objectif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('URGENCE', "Fonds d'urgence"), ('ACHAT', 'Achat important'), ('VACANCES', 'Vacances'), ('EDUCATION', 'Éducation'), ('RETRAITE', 'Retraite'), ('DETTE', 'Remboursement de dette'), ('AUTRE', 'Autre')], max_length=20)),
                ('montant_cible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIF', 'En cours'), ('TERMINE', 'Atteint'), ('PAUSE', 'En pause'), ('ABANDONNE', 'Abandonné')], default='ACTIF', max_length=20)),
                ('contribution_automatique', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frequence_contribution', models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle'), ('annuelle', 'Annuelle')], default='mensuelle', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_realisation', models.DateTimeField(blank=True, null=True)),
                ('est_complete', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AlterField(
            model_name='contribution',
            name='objectif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='goals.objectif'),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
