# Generated by Django 5.1.6 on 2025-05-03 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_objectif_alter_contribution_objectif_delete_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('atteint', models.BooleanField(default=False)),
                ('date_atteinte', models.DateTimeField(blank=True, null=True)),
                ('objectif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jalons', to='goals.objectif')),
            ],
        ),
    ]
