# Generated by Django 5.1.6 on 2025-05-04 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_jalon'),
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='montant_depense',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='seuil_objectif',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='objectif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='goals.objectif'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('JALON', 'Jalon atteint'), ('ECHEANCE', 'Proximité échéance'), ('RAPPEL', 'Rappel contribution'), ('SUGGESTION', "Suggestion d'amélioration"), ('BUDGET', 'Alerte budget')], default='RAPPEL', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
