# Generated by Django 5.1.5 on 2025-05-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='montant',
        ),
        migrations.AddField(
            model_name='depense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
