# Generated by Django 5.1.5 on 2025-05-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomcategorie', models.CharField(choices=[('alimentaire', 'Alimentaire'), ('location', 'Location'), ('voiture', 'Voiture'), ('divertissement', 'Divertissement'), ('transport', 'Transport'), ('facture', 'Facture'), ('famille', 'Famille'), ('hopital', 'Hopital')], max_length=100, unique=True)),
            ],
        ),
    ]
