# Generated by Django 4.2.16 on 2025-05-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='Nomcategorie',
            field=models.CharField(choices=[('alimentaire', 'Alimentaire'), ('location', 'Location'), ('voiture', 'Voiture'), ('divertissement', 'Divertissement'), ('transport', 'Transport'), ('facture', 'Facture'), ('famille', 'Famille'), ('hopital', 'Hopital'), ('autres', 'Autres')], max_length=100, unique=True),
        ),
    ]
